title: 'Hello,World!'
description: 
keyword: 
url: 'https://bentsai7.github.io'
baseurl: '/'
# Navigation links
nav:
  home: '/'
  tags: '/tags.html'
# Footer
footer:
  since: 2019
# Author
author: Ben Tsai
nickname: 
bio: 
avatar: ''
# Search
search: true
# Night mode
nightMode: true
# MathJax
mathjax: true
# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']
theme-color: 'default'
postPatterns: 'circuitBoard'
sns:
  twitter:
  email: bentsai@gmail.com
  facebook: 
  github: 

recommend-tags: false # whether or not display recommend-tags on the sidebar
recommend-condition-size: 0 # a tag will be recommended if the size of it is more than this value
# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']
# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
# RSS
RSS: false
permalink: /:year/:month/:day/:title.html
# Plugins
plugins: [jekyll-paginate]
